### ISSUE TITLE
Mocha tests

### ISSUE THREAD

**Issue by chase-moskal** [ChaseMoskal/Cynic#5]
> Ideally, all tests should be run through a common suite of many possible input types --both in chain context, and in static context.
> Since ticket #3, tests should be tested 'naked' context (directly on the `tests` object) as well.

_Done when:_
- Mocha is running Chai tests.
- All Cynic tests are run through with a myriad of inputs, covering every type of JS value, just to check for runtime errors.
- At least one meaningful assertion for each Cynic test.

**Comment by ChaseMoskal** [comment]
Still don't have any tests that run in naked context...

**Comment by chase-moskal** [comment]
I can't think of any strong reasons why I chose tape over Mocha. I miss Chai a little bit.

I think we should switch back to Mocha before writing too many tests.
